/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rhora.h"

segactual *
obten_segundos_1_svc(void *argp, struct svc_req *rqstp)
{
	static segactual  result;

	/*
	 * insert server code here
	 */

	return &result;
}
