/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rhora.h"


void
hora_program_1(char *host)
{
	CLIENT *clnt;
	segactual  *result_1;
	char *obten_segundos_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, HORA_PROGRAM, HORA_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = obten_segundos_1((void*)&obten_segundos_1_arg, clnt);
	if (result_1 == (segactual *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	hora_program_1 (host);
exit (0);
}
